export const ADD_HAVE_READ = 'ADD_HAVE_READ';
export const REMOVE_HAVE_READ = 'REMOVE_HAVE_READ';

export const ADD_AM_READING = 'ADD_AM_READING';
export const REMOVE_AM_READING = 'REMOVE_AM_READING';

export const ADD_WISHLIST = 'ADD_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';
